export default [
	"views-field-field-1-fecha",
	"views-field-field-4-pa-s",
	"views-field-field-3-departamento",
	"views-field-field-4-municipio",
	"views-field-field-selecciona-tu-comunidad-es",
	"views-field-field-6-nombre-y-apellido",
	"views-field-field-7-tienes-tu-pfo-plan-forma",
	"views-field-title",
	"views-field-field-9-tu-pfo-est-vinculado-a-l",
	"views-field-field-10-cu-les-te-parecen-que-s",
	"views-field-field-aclarar-otros-aprendizajes",
	"views-field-field-11-est-s-estudiando-",
	"views-field-field-12-est-s-trabajando-",
	"views-field-field-13-te-interesar-a-vivir-en",
	"views-field-field-13-1-por-qu-",
	"views-field-field-14-est-s-relacionado-a-aso",
	"views-field-field-sexo"
]
